### ISSUE TITLE
Environment for test coverage

### ISSUE THREAD

**Issue by maelle** [ropenscilabs/pkgreport#14]
When running `covr`, is it with `NOT_CRAN` set to TRUE?

**Comment by mpadge** [comment]
`covr` has no `NOT_CRAN` parameter. The call itself from `gp` is just a [default call](https://github.com/MangoTheCat/goodpractice/blob/master/R/prep_covr.R#L7-L8), and so using the parameter values from [`package_coverage()`](https://covr.r-lib.org/reference/package_coverage.html), which defaults to `type = "tests"`. As you see in the first link, that's hard-coded and cannot be changed. I suspect we'll eventually need to implement our own `gp`, but calling each component separately to allow more control over such things. I'm happy for now to continue with hard-coded defaults of `gp`, and leave that for later. Thoughts?

**Comment by maelle** [comment]
I mean an environmental variable, sorry.

I'd just like to be sure we're not measuring test coverage whilst excluding tests "skipped on CRAN", maybe that's the default behavior?

**Comment by mpadge** [comment]
'covr' itself just relies for test coverage on a single call to [`tools::testInstalledPackage()`](https://github.com/r-lib/covr/blob/ad895caf86e0cd106b835098c3849759e7763f64/R/covr.R#L362) that is embedded within a `withr::with_envvar()` call. That should mean that no environmental variables will be skipped, even if somehow calling `covr` within a fake CRAN environment. (And `skip_on_cran` flags in `testthat` work by setting additional flags that are themselves set in response to the [CRAN env vars](https://cran.r-project.org/doc/manuals/r-release/R-ints.html#Tools), so none of that can be carried through at all to the `covr` environment used for the call.) The result should be complete testing and complete ignoring of any `skip_` type flags.

**Comment by mpadge** [comment]
One note that may be important: `gp` only ever calls `covr` with all default values, which means it only reports coverage from tests alone, and so excludes potentially additional coverage from examples and vignettes. We might need to address that at some stage.
